from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 481)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(240, 40, 221, 381))
        self.groupBox.setObjectName("groupBox")
        self.threeone = QtWidgets.QPushButton(self.groupBox)
        self.threeone.setGeometry(QtCore.QRect(30, 60, 161, 41))
        self.threeone.setObjectName("threeone")
        self.threetwo = QtWidgets.QPushButton(self.groupBox)
        self.threetwo.setGeometry(QtCore.QRect(30, 130, 161, 41))
        self.threetwo.setObjectName("threetwo")
        self.threethree = QtWidgets.QPushButton(self.groupBox)
        self.threethree.setGeometry(QtCore.QRect(30, 210, 161, 41))
        self.threethree.setObjectName("threethree")
        self.threefour = QtWidgets.QPushButton(self.groupBox)
        self.threefour.setGeometry(QtCore.QRect(30, 280, 161, 41))
        self.threefour.setObjectName("threefour")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(520, 40, 221, 381))
        self.groupBox_2.setObjectName("groupBox_2")
        self.fourone = QtWidgets.QPushButton(self.groupBox_2)
        self.fourone.setGeometry(QtCore.QRect(30, 60, 161, 41))
        self.fourone.setObjectName("fourone")
        self.fourtwo = QtWidgets.QPushButton(self.groupBox_2)
        self.fourtwo.setGeometry(QtCore.QRect(30, 130, 161, 41))
        self.fourtwo.setObjectName("fourtwo")
        self.fourthree = QtWidgets.QPushButton(self.groupBox_2)
        self.fourthree.setGeometry(QtCore.QRect(30, 210, 161, 41))
        self.fourthree.setObjectName("fourthree")
        self.fourfour = QtWidgets.QPushButton(self.groupBox_2)
        self.fourfour.setGeometry(QtCore.QRect(30, 280, 161, 41))
        self.fourfour.setObjectName("fourfour")
        self.loadimage = QtWidgets.QPushButton(self.centralwidget)
        self.loadimage.setGeometry(QtCore.QRect(40, 210, 161, 41))
        self.loadimage.setObjectName("loadimage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "2022 opencvdl HW1_2"))
        self.groupBox.setTitle(_translate("MainWindow", "3. Edge Detection"))
        self.threeone.setText(_translate("MainWindow", "3.1 Gaussian Blur"))
        self.threetwo.setText(_translate("MainWindow", "3.2 Sobel X"))
        self.threethree.setText(_translate("MainWindow", "3.3 Sobel Y"))
        self.threefour.setText(_translate("MainWindow", "3.4 Magnitude"))
        self.groupBox_2.setTitle(_translate("MainWindow", "4. Translation"))
        self.fourone.setText(_translate("MainWindow", "4.1 Resize"))
        self.fourtwo.setText(_translate("MainWindow", "4.2 Translation"))
        self.fourthree.setText(_translate("MainWindow", "4.3 Rotation, Scaling"))
        self.fourfour.setText(_translate("MainWindow", "4.4 Shearing"))
        self.loadimage.setText(_translate("MainWindow", "load image"))
