# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(468, 688)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Resnet = QtWidgets.QGroupBox(self.centralwidget)
        self.Resnet.setGeometry(QtCore.QRect(50, 40, 361, 601))
        self.Resnet.setObjectName("Resnet")
        self.loadimage = QtWidgets.QPushButton(self.Resnet)
        self.loadimage.setGeometry(QtCore.QRect(50, 60, 261, 51))
        self.loadimage.setObjectName("pushButton")
        self.fiveone = QtWidgets.QPushButton(self.Resnet)
        self.fiveone.setGeometry(QtCore.QRect(50, 140, 261, 51))
        self.fiveone.setObjectName("fiveone")
        self.fivetwo = QtWidgets.QPushButton(self.Resnet)
        self.fivetwo.setGeometry(QtCore.QRect(50, 230, 261, 51))
        self.fivetwo.setObjectName("fivetwo")
        self.fivethree = QtWidgets.QPushButton(self.Resnet)
        self.fivethree.setGeometry(QtCore.QRect(50, 320, 261, 51))
        self.fivethree.setObjectName("fivethree")
        self.fivefour = QtWidgets.QPushButton(self.Resnet)
        self.fivefour.setGeometry(QtCore.QRect(50, 410, 261, 51))
        self.fivefour.setObjectName("fivefour")
        self.fivefive = QtWidgets.QPushButton(self.Resnet)
        self.fivefive.setGeometry(QtCore.QRect(50, 500, 261, 51))
        self.fivefive.setObjectName("fivefive")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Resnet.setTitle(_translate("MainWindow", "ResNet50"))
        self.loadimage.setText(_translate("MainWindow", "Load Image"))
        self.fiveone.setText(_translate("MainWindow", "5.1 Show Images"))
        self.fivetwo.setText(_translate("MainWindow", "5.2 Show Distribution"))
        self.fivethree.setText(_translate("MainWindow", "5.3 Show Model Structure"))
        self.fivefour.setText(_translate("MainWindow", "5.4 Show Comparison"))
        self.fivefive.setText(_translate("MainWindow", "5.5 Inference"))
