# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 579)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 50, 321, 491))
        self.groupBox.setObjectName("groupBox")
        self.loadimage = QtWidgets.QPushButton(self.groupBox)
        self.loadimage.setGeometry(QtCore.QRect(50, 50, 221, 41))
        self.loadimage.setObjectName("loadimage")
        self.one = QtWidgets.QPushButton(self.groupBox)
        self.one.setGeometry(QtCore.QRect(50, 120, 221, 41))
        self.one.setObjectName("one")
        self.two = QtWidgets.QPushButton(self.groupBox)
        self.two.setGeometry(QtCore.QRect(50, 190, 221, 41))
        self.two.setObjectName("two")
        self.three = QtWidgets.QPushButton(self.groupBox)
        self.three.setGeometry(QtCore.QRect(50, 260, 221, 41))
        self.three.setObjectName("three")
        self.four = QtWidgets.QPushButton(self.groupBox)
        self.four.setGeometry(QtCore.QRect(50, 330, 221, 41))
        self.four.setObjectName("four")
        self.five = QtWidgets.QPushButton(self.groupBox)
        self.five.setGeometry(QtCore.QRect(50, 400, 221, 41))
        self.five.setObjectName("five")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(420, 130, 320, 320))
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "VGG19 Test"))
        self.loadimage.setText(_translate("MainWindow", "Load Image "))
        self.one.setText(_translate("MainWindow", "1. Show Train Images"))
        self.two.setText(_translate("MainWindow", "2. Show Model Structure"))
        self.three.setText(_translate("MainWindow", "3. Show Data Augmentation"))
        self.four.setText(_translate("MainWindow", "4. Show Accuracy and Loss"))
        self.five.setText(_translate("MainWindow", "5. Inference"))
